InventoryManagementProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Inventoryapp.urls')),

]

Inventoryapp/urls.py
from django.urls import path
from Inventoryapp.views import Ordercreation, ProductDisplay, ProductEntry, ProductPage

app_name = 'Inventoryapp'
urlpatterns = [
 path('ProductEntry/',ProductEntry.as_view(),name="ProductEntry"),
 path('ProductPage/',ProductPage.as_view()),
 path('ProductDisplay/',ProductDisplay.as_view(),name="ProductDisplay"),
 path('Ordercreation/',Ordercreation.as_view(),name="Ordercreation")
]

Inventoryapp/models.py
from django.db import models

# Create your models here.


class InventoryappOrdertbl(models.Model):
    id = models.BigAutoField(primary_key=True)
    quantity = models.IntegerField(db_column='Quantity')  # Field name made lowercase.
    totalprice = models.IntegerField(db_column='TotalPrice')  # Field name made lowercase.
    date = models.CharField(max_length=100)
    productid = models.ForeignKey('InventoryappProduct', models.DO_NOTHING, db_column='productid')

    class Meta:
        managed = False
        db_table = 'inventoryapp_ordertbl'


class InventoryappProduct(models.Model):
    name = models.CharField(db_column='Name', max_length=100)  # Field name made lowercase.
    category = models.CharField(db_column='Category', max_length=50)  # Field name made lowercase.
    quantity = models.IntegerField(db_column='Quantity')  # Field name made lowercase.
    price = models.IntegerField(db_column='Price')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'inventoryapp_product'


class InventoryappSuppliertbl(models.Model):
    name = models.CharField(db_column='Name', max_length=100)  # Field name made lowercase.
    contact = models.CharField(db_column='Contact', max_length=100)  # Field name made lowercase.
    productid = models.ForeignKey(InventoryappProduct, models.DO_NOTHING, db_column='productid')

    class Meta:
        managed = False
        db_table = 'inventoryapp_suppliertbl'

Inventoryapp/views.py
from urllib import request
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from datetime import datetime as dt


from Inventoryapp.models import InventoryappOrdertbl, InventoryappProduct

# Create your views here.

class ProductPage(View):
    def get(self,request):
        return render(request,'productupload.html')

class ProductEntry(View):
    def post(self,request):
        Name = request.POST['Name']
        Category = request.POST['Category']
        Quantity =request.POST['Quantity']
        Price = request.POST['Price']
        result = InventoryappProduct(Name=Name,Category=Category,Quantity=Quantity,Price=Price)
        result.save()
        return JsonResponse({"status":"success"})
    
    
       
    
class ProductDisplay(View):
    def get(self,request):
        data = InventoryappProduct.objects.all()
        return render(request,'productview.html',{'data':data})
    
class Ordercreation(View):
    def get(self,request):
        data = InventoryappProduct.objects.all()
        return render(request,'OrderCreation.html',{'data':data})
    


class OrderCreation(View):
    def post(self,request):
        proudctid = request.POST['productid']
        Quantity = request.POST['Quantity']
        TotalPrice = request.POST['TotalPrice']
        date =dt.now()
        result = InventoryappOrdertbl(quantity=Quantity,totalprice=TotalPrice,date=date,productid=proudctid)
        result.save()
        data = InventoryappProduct.objects.get(id= proudctid)
        stock_decraese =  data.Quantity - 1
        data.Quantity = stock_decraese
        data.save()
        return JsonResponse({"status":"success"})

templates/OrderCreation.html
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <style>
            h1{
                text-align: center;
            }
        </style>
    </head>

    <body>
<h1>
    Order  Creation
</h1>
<form method="POST" action="{% url 'Inventoryapp:ProductEntry' %}" class="form-control">
    {% csrf_token %} 
    <div class="container">
<div class="row">
    <div class="col-sm-6">
        <in<put type="text" placeholder="Product Name" name="Name">>
    </div>
    <div class="col-sm-6">
        <input type="text" placeholder="Category" name="Category">
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <input type="text" placeholder="Quantity" name="Quantity">
    </div>
    <div class="col-sm-6">
        <input type="text" placeholder="Price" name="Price">
    </div>
</div>
</div>
<input type="submit" value="upload">
</form>
    </body>
</html>

templates/productupload.html
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <style>
            h1{
                text-align: center;
            }
        </style>
    </head>

    <body>
<h1>
    Product Uploads
</h1>
<form method="POST" action="{% url 'Inventoryapp:ProductEntry' %}" class="form-control">
    {% csrf_token %} 
    <div class="container">
<div class="row">
    <div class="col-sm-6">
        <input type="text" placeholder="Product Name" name="Name">
    </div>
    <div class="col-sm-6">
        <input type="text" placeholder="Category" name="Category">
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <input type="text" placeholder="Quantity" name="Quantity">
    </div>
    <div class="col-sm-6">
        <input type="text" placeholder="Price" name="Price">
    </div>
</div>
</div>
<input type="submit" value="upload">
</form>
    </body>
</html>

templates/productview.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>

<h2>HTML Table</h2>

<table>
  <tr>
    <th>Product Name</th>
    <th>Quantiy</th>
    <th>stock Level</th>
    <th>Price</th>
  </tr>
  {% for i in data %}
  <tr>
   <td>{{i.Name}}</td>
   <td>{{i.Category}}</td>
   <td>{{i.Quantity}}</td>
   <td>{{i.Price}}</td>
  </tr>
 {% endfor %}
</table>

</body>
</html>